apiVersion: apps/v1
kind: Deployment
metadata:
  name: condor-pagos
  labels:
    app: condor-pagos
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: condor-pagos
  template:
    metadata:
      labels:
        app: condor-pagos
    spec:
      containers:
        - name: condor-pagos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
